server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
pagehelper:
  helper-dialect: mysql      
file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'E:\\file'